apiVersion: v2
name: co-web
description: A Helm chart for the Curious Outcomes Communities web UI
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: curious-human-lib
    repository: "file://../lib"
    version: ~0.0.1
    tags:
      - library
      - shared
