apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml
- issuer.yaml
- co-api-mongodb.prod.yaml

patchesStrategicMerge:
- patches/deployment.rmv-debug.patch.yaml
- patches/ingress.add-tls.patch.yaml
- patches/co-api.mongodb.delete.yaml

replacements:
- path: patches/co-api-mongodb.replacement.yaml

namespace: production