apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-co
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    co-event:
      owner: curioushuman
      repository: curious-outcomes-communities
      webhook:
        endpoint: /github
        port: "12000"
        method: POST
        url: http://argo-events.curious-outcomes.community
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
