apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-co
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-co-eventsource
      eventSourceName: github-co
      eventName: co-event
  triggers:
  - template:
      name: github-co-trigger
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: github-co-trigger-
              labels:
                app: github-co-trigger
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args: ["This is the repo URL:\n", ""]
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: github-co-source
              dataKey: body.repository.git_url
            dest: spec.containers.0.args.1
