apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- co-api-mongodb.staging.yaml

patchesStrategicMerge:
- patches/deployment.namespace.patch.yaml
- patches/ingress.staging.patch.yaml
- patches/co-api.mongodb.delete.yaml

replacements:
- path: patches/co-api-mongodb.replacement.yaml

namespace: staging