apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: co-certificate
  # Namespace will be added by ArgoCD
  # namespace: argocd
spec:
  dnsNames:
    - api.curious-outcomes.community
  secretName: letsencrypt-co-secret
  issuerRef:
    name: letsencrypt-co
    kind: ClusterIssuer