apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: co-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: core/co-api/overlays/production
    repoURL: https://github.com/curioushuman/curious-outcomes-k8s.git
    targetRevision: HEAD
    kustomize:
      # https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/
      images:
      - curioushuman/curious-outcomes-api:0.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

