apiVersion: v2
name: co-api
description: A Helm chart for the Curious Outcomes Communities API
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: curious-human-lib
    repository: "file://../lib"
    version: ~0.0.1
    tags:
      - library
      - shared
  # https://artifacthub.io/packages/helm/bitnami/mongodb
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: ~11.1.10
    tags:
      - database
      - mongodb
